version: '3'
services:
  auth2_proxy:
    image: bitnami/oauth2-proxy:7.3.0
    container_name: auth2_proxy
    restart: always
    depends_on:
      - nginx
    environment:
      config: /etc/oauth2-proxy.cfg
    volumes:
      - ./oauth2-proxy.cfg:/etc/oauth2-proxy.cfg:ro

  nginx:
    image: nginx:1.23
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./nginx_html:/data/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_logs:/logs

